name: deploy_as_static_in_gh_pages_branch
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
      if: success()
    - run: echo "******************************************************"
      if: success()
    - run: cp -a $GITHUB_WORKSPACE/dist/angular-tempate/. $GITHUB_WORKSPACE/docs
    - run: ls  -R $GITHUB_WORKSPACE/ -Inode_modules -Isrc 
    - run: git status
    - run: git add $GITHUB_WORKSPACE/docs/
    - run: git status
    - run: pwd
      if: success()
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ github.token }}
        push-branch: 'master'
        commit-message: 'build files'
        force-add: 'true'
        files: /home/runner/work/Angular-template/Angular-template/dist/
        name: Mateen
        email: makjavaprogrammer@gmail.com 
    
