name: deploy_as_static_in_gh_pages_branch
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
      if: success()
    - run: echo "******************************************************"
    
    
      if: success()
    - uses: actions/checkout@v3
      with:
        node-version: '16'
        path: build
        ref: build
      if: success()
    - run: echo "******************************************************"
    - run: cp -a $GITHUB_WORKSPACE/dist/angular-tempate/. $GITHUB_WORKSPACE/build/public
    - run: ls  -R $GITHUB_WORKSPACE/ -Inode_modules -Isrc 
    - run: cd $GITHUB_WORKSPACE/build/public
    - run: pwd
      if: success()
    - name: action-push
      uses: ludeeus/action-push@0.0.1

      
    
