name: deploy_as_static_in_gh_pages_branch
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ github.token  }} 
          build_configuration: production 
          base_href: /Angular-template/  
          deploy_branch: gh-pages 
          angular_dist_build_folder: dist/Angular-template
