name: Build and Deploy Assets
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Assets
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: Install deps and build
        run: npm install; npm run build

      - name: Deploy
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: build
          target_owner: mateenkhan
          target_repo: Angular-template
          target_dir: public
          target_branch: build # default
          # Optional
          access_token: ${{ github.tokem }}
          cleanup_command: "rm -rf assets/* && rm -f assets/asset-manifest.json"
