name: deploy_as_static_in_gh_pages_branch
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: mkdir /home/runner/work/Angular-template/static
    - run: ls  -R $GITHUB_WORKSPACE -Isrc 
    - run: npm install
    - run: ls  -R $GITHUB_WORKSPACE -Inode_modules -Isrc 
    - run: echo "runinng build"
    - run: npm run build
    - run: echo "after build"
    - run: git branch -a
      if: success()
    - run: echo "******************************************************"
    - run: ls -ltr $GITHUB_WORKSPACE/dist/angular-tempate
    
    - run: cd /home/runner/work/Angular-template/static
    - run: git clone https://github.com/MateenKhan/Angular-template.git -b build
      if: success()
    - run: ls -ltr /home/runner/work/Angular-template/static/
    - run: cd /home/runner/work/Angular-template/static/Angular-template
    - run: git branch
    - run: ls -ltr $GITHUB_WORKSPACE/dist/angular-tempate
    - run: cp -a $GITHUB_WORKSPACE/dist/angular-tempate/. /home/runner/work/Angular-template/static
    - run: ls -ltr /home/runner/work/Angular-template/static
#     - run: /usr/bin/bash -e "cd $GITHUB_WORKSPACE/dist "
#     - run: pwd
#     - run: cd /usr/bin/bash -e "$GITHUB_WORKSPACE/dist/angular-tempate"
#     - run: pwd
#     - run: ls -ltr
#     - run: ls -ltr $GITHUB_WORKSPACE/dist/angular-tempate
    - run: git remote -v
    - run: echo "******************************************************"
      if: success()
#     - run: pwd
#     - run: cd $GITHUB_WORKSPACE/dist/angular-tempate /usr/bin/bash
#     - run: pwd
#     - run: git init
#     - run: git remote set-url origin https://MateenKhan:Breathe%402021github.com/MateenKhan/Angular-template.git
#     - run: git checkout -b build remotes/origin/build
    - run: git add *
#     - run: git checkout remotes/origin/build -b build
    - run: git commit -m "uploading build files"
    - run: git push --force
    
#       if: success()
#     - uses: sterlingwes/gh-pages-deploy-action@v1.1
#       with:
#         access-token: ${{ github.token }}
#         source-directory: $GITHUB_WORKSPACE/dist/angular-tempate
#         build-command: npm run build
#     - uses: avinal/github-pages-deploy-action@main
#       with:
#         GITHUB_TOKEN: ${{ github.token }}
#         # For python write python package and additional packages if any - "python3 python3-pip" 
#         LANGUAGE: "angular"
#         # Write make command to generate html e.g.- "make html"
#         MAKE_COMMAND: "npm run build"
#         # Write the branch name for storing github pages source 
#         PAGES_BRANCH: "build"
#         # Write the branch name having source files for site/documentation
#         BUILD_FROM: "master"
#         # Write the name of the output folder where generated html is stored by makefile.
#         DOCS_FOLDER: "$GITHUB_WORKSPACE/dist/angular-tempate"
    
    
#     - name: Deploy to GitHub Pages
#       if: success()
#       uses: crazy-max/ghaction-github-pages@v2
#       with:
#         target_branch: build
#         build_dir: $GITHUB_WORKSPACE/dist/angular-tempate
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
