name: Build and Deploy Assets
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Assets
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ gitlab.token }}

      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: Install deps and build
        run: npm install; npm run build

      - name: Deploy
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: build
          target_owner: mateenkhan
          target_repo: angular-template
          target_dir: public
          target_branch: build # default
          # Optional
          # access_token: ${{ secrets.GITHUB_ACCESS_TOKEN }} # Not needed when using SSH
          cleanup_command: "rm -rf assets/* && rm -f assets/asset-manifest.json"
